[V360-8809] feat testing : Alert test cases
ValidereInc/common-components pull request #392
Opened 2021-11-25 20:56 UTC by NamrataAjmeri

## Scope
- [x] Enhancement: backwards-compatible functionality added
- [ ] Bug-Fix / Patch: backwards-compatible bug fix / revision
- [ ] RFC: request for comments; discussion only

## Context
Wrote unit test cases for Alerts.

## Summary of Changes
Wrote unit test cases for following files 
- Alert.js
- AlertProvider.js
- AlertHelper.js

## Pre-Merge Checklist
- [ ] Changelog entry? (Summary in `/changelog/<section>/<issue_number>.md`)
- [ ] Linked to [Jira issue](https://support.atlassian.com/bitbucket-cloud/docs/use-smart-commits/) ?
- [ ] Labels tagged?

2021-11-25 21:08 UTC, chungcareer commented
run `npm run prettier` to clear linting issue and install [eslint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) on your vscode

2021-11-26 13:44 UTC, chungcareer approved these changes

2021-11-26 13:51 UTC, johnisr commented on package.json
> +    "coverage": "jest test --env=jsdom --coverage",
![Screen Shot 2021-11-26 at 8 40 02 AM](https://user-images.githubusercontent.com/34279434/143589582-ef499e6d-906a-4b27-88f1-38ebf9bd2a47.png)

Great job on Alert and AlertHelper, seems like both have 100% coverage. Would like to see some more coverage on AlertProvider and useManageAlerts though.

2021-11-26 13:51 UTC, johnisr commented on src/Alert/Alert.test.js
> +import { render, fireEvent, screen } from "@testing-library/react";
screen doesn't seem to be used

2021-11-26 13:51 UTC, johnisr commented on src/Alert/Alert.tsx
> +      </span>
When testing, I try not to change the source code unless absolutely necessary or there's justification for doing so. I think other queries should be prioritized first, as seen in the [react-testing-library docs](https://testing-library.com/docs/queries/about/#priority).

In this case, `queryByText` would work as is with Alerts but after seeing the priority list, the Alert component should have the `alert` role and it would be justified to add that in. We can then use `queryByRole("alert") to find it.

```
<div
  className={`${cx("alert", variantClassName, {
    "alert--truncated": showIcon,
  })} ${className}`}
  style={style}
  role="alert"
>
```

2021-11-26 13:51 UTC, johnisr commented on src/Alert/Alert.tsx
> +          data-testid="on-close-id"
Related to above, the close icon in alert is not accessible at all. We can make it clearer to screen readers by using `role="button"` as well as `aria-label="close"` props to make it more visible and we can then use the `queryByRole("button", { name: "close"})` or `queryByLabelText("close")` to find it.

I haven't thought about accessibility much, which is why these components don't have these props in the first place. But if there really is no way for `react-testing-library` to find them without resorting to `queryByTestId`, it's better to look up the above accessibility attributes and see if they're applicable before going to the last resort `data-testid`.

2021-11-26 14:03 UTC, johnisr commented on src/Alert/Alert.test.js
> +  });
While I do see the merits of unit testing, I'd want to stick to the [guiding principles of react-testing-library](https://testing-library.com/docs/guiding-principles/): "The more your tests resemble the way your software is used, the more confidence they can give you." Another way the react-testing-library author says this is: ["Write tests. Not too many. Mostly Integration"](https://kentcdodds.com/blog/write-tests). More info on the [difference between test types](https://kentcdodds.com/blog/static-vs-unit-vs-integration-vs-e2e-tests).

We do have E2E testing but it takes quite a while for it to ru (~10-12 minutes for each browser and we test 4 browsers), so we limit running it only when we have a release candidate ready. Integration tests should be the main focus, as they are fast enough to be run every PR as well as close enough to the way software is used.

Here is an example that you can use to start off with integration testing:
```
import React from "react";
import {
  render,
  fireEvent,
  waitForElementToBeRemoved,
} from "@testing-library/react";
import { AlertProvider, Button, useAlert } from "..";

const MockAlerts = ({ message }) => {
  const { addAlert, removeAlert } = useAlert();

  const addButtonClick = () => {
    addAlert({
      variant: "success",
      message: message,
    });
  };

  return (
    <div>
      <Button onClick={() => removeAlert()}>Remove Alert</Button>

      <Button onClick={() => addButtonClick()}>Add Alert</Button>
    </div>
  );
};

describe("Alert tests", () => {
  test("some test", async () => {
    const message = "Some Message";
    const { queryByText, queryByLabelText, queryByRole } = render(
      <AlertProvider timeout={100}>
        <MockAlerts message={message} />
      </AlertProvider>
    );

    const removeAlertButton = queryByText("Remove Alert");
    const addAlertButton = queryByText("Add Alert");

    fireEvent.click(addAlertButton);

    expect(queryByRole("alert").textContent).toEqual(message);

    expect(queryByLabelText("close")).toBeTruthy();

    await waitForElementToBeRemoved(() => queryByRole("alert"));

    expect(queryByRole("alert")).toBeFalsy();
  });
});
```
It makes changes to the `Alert` component so we can use better queries as mentioned below. 

This is exactly how we use `AlertProvider` and `useAlert` in code (currently in esg-frontend, and also in `Alert.stories.js`). With the `MockAlert` component as the basis, we can test out pretty much everything (e.g. is `maxAlerts` adhered to, can clicking on a specific close icon close the specific alert, see if the order is correct if placement is top instead of bottom, see if they are removed in the right order, etc.)

The above might require a more extensive knowledge of `react-testing-library` queries and api, so try your best and do as much as you can, no need to go for full 100% coverage.

2021-11-30 14:39 UTC, chungcareer approved these changes

2021-12-01 14:05 UTC, johnisr approved these changes

2021-12-01 14:34 UTC, johnisr requested changes

2021-12-01 14:34 UTC, johnisr commented on src/Alert/Alert.tsx
> +        </button>
Make sure to check the components' stories if making changes to the component. While button may be better in this case, it changed the design as well. Adding tests shouldn't change the functionality and design of the components.

![Screen Shot 2021-12-01 at 9 32 26 AM](https://user-images.githubusercontent.com/34279434/144253116-08a94699-c5ab-4a8c-8416-7d86ee37301c.png)

2021-12-01 14:43 UTC, johnisr commented on src/Alert/useManageAlerts.tsx
> +    }
I would revert this change. the latter part is meant to run every time (e.g. `addAlert` always adds an alert). This change makes it so that when `maxAlerts` is reached, it just removes an already existing alert and not add a new one to take its place. 

Make sure to check the storybook or play around with the component in other repos if making changes to the actual component to make sure it still functions the same

2021-12-01 15:30 UTC, johnisr commented on src/Alert/AlertProvider.test.js
> +  });
correct me if I'm wrong, but it seems like the if/else block that was added in `useManageAlerts` was added because of this test failing when `fireEvent(addAlertButton)` was called 6 times and the `queryAllByRole` had length 6 instead of the max 5. 

If a test isn't going how you'd expect, do a sanity check first by using it in storybook or similar. In this case, it's because the assert statement happens right away while the first Alert is starting its exit animation and the last Alert is doing its enter animation.

The common mistakes article from the library author shows a bunch of good practices, including how to possibly resolve this error. https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#performing-side-effects-in-waitfor

```
  test("Alert message should get deleted when exceeds max alerts", async () => {
    const message = "Test Message";
    const maxAlerts = 3;
    const { queryByText, queryAllByRole } = render(
      <AlertProvider maxAlerts={maxAlerts}>
        <MockAlerts message={message} />
      </AlertProvider>
    );

    const addAlertButton = queryByText("Add Alert");

    for (let i = 0; i < maxAlerts + 1; i++) {
      fireEvent.click(addAlertButton);
    }

    waitFor(() => {
      expect(queryAllByRole("alert").length).toEqual(maxAlerts);
    });
  });
```
Note: The code above only passes if the `if/else` block in `useManageAlerts` is reverted.

2021-12-02 14:34 UTC, NamrataAjmeri commented on src/Alert/AlertProvider.test.js
> +  });
@johnisr I have done the required changes.

2021-12-02 14:35 UTC, NamrataAjmeri commented on src/Alert/Alert.tsx
> +        </button>
@johnisr I have done the requires changes in the scss file.

2021-12-02 14:36 UTC, NamrataAjmeri commented on src/Alert/useManageAlerts.tsx
> +    }
@johnisr Yes I removed the else block.

2021-12-02 16:26 UTC, johnisr reviewed
Great job, the coverage looks good.

![Screen Shot 2021-12-02 at 11 06 46 AM](https://user-images.githubusercontent.com/34279434/144462144-45509e55-8448-40f1-bb03-1c45a09cecf8.png)

2021-12-02 16:26 UTC, johnisr commented on src/Alert/Alert.module.scss
```suggestion
  background-color: transparent;
  padding: 0px;
```
While using more semantic html is great, we have to be cautious of other stylesheets that the other repos will use. The operations hub uses the `react-bootstrap` stylesheet, as does the commercial hub (and some other ones...). This might result in some unintended styling applied.

In this case, using the `button` added an extra padding which shifted the close icon more to the left than the design intended (though it's not because of bootstrap, rather because of chrome default styling <-- could be dealt with normalize.css or other resetters).

![Screen Shot 2021-12-02 at 11 16 43 AM](https://user-images.githubusercontent.com/34279434/144460452-01d66f70-2240-4be0-9219-f483bc646d89.png)
 
So when making changes to any of the common components, make sure to check how it was before/after and see if there's any UI changes and try to resolve them. If you have Figma access, you can check the design guideline that all the common-components are based off of (link for Alerts: https://www.figma.com/file/N9LjAbtbOpOXNOIJ9ps5f4/MSKTRS-Design-System-Centre?node-id=1758%3A26640). Ask Chung if you don't have access yet. If you have a local copy of the other repos (e.g. operations hub), you can also check if it has changed there if `COMMON_COMPONENT_PATH` is set up properly in those repos.

2021-12-02 18:45 UTC, johnisr approved these changes

2021-12-02 18:47 UTC, merged